[env]
ENV = "local"

[build]
rustflags = ["-C", "target-cpu=native", "--cfg=has_std"]

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
panic = "abort"
rpath = false
incremental = false